name: On new version tag

on:
  push:
    tags:
      - v* # Version tags

jobs:
  npm-publish:
    if: false # disable for now
    name: Publish NPM package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
      - name: Prepare
        run: npm ci
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          if [ -z "${NODE_AUTH_TOKEN}" ]; then
            echo "NODE_AUTH_TOKEN is undefined"
            exit 1
          fi
          npm publish --access public
