name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-and-lint:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run test
      - run: npm run lint
